development:
  adapter: postgresql
  database: madeinpgh_dev
  encoding: utf8

  # this works for local development as well
  # adapter: sqlite3
  # database: db/development.sqlite3
  # pool: 5
  # timeout: 5000

test:
  adapter: postgresql
  database: madeinpgh_test
  encoding: utf8
